### PR TITLE
📦 Add @ianvs/prettier-plugin-sort-imports and update import order

### PR DESCRIPTION
**Pull request by kyziq**
this PR introduces [@ianvs/prettier-plugin-sort-imports](https://github.com/IanVS/prettier-plugin-sort-imports) (improved [@trivago/prettier-plugin-sort-imports](https://github.com/trivago/prettier-plugin-sort-imports)) to ensure consistent import order across project. The following import order is applied:

```json
  "importOrder": ["^react", "<THIRD_PARTY_MODULES>", "", "^@/(.*)$", "^[./]"]
```

example of new import order:

```ts
import { useNavigate } from 'react-router-dom'
import { User2 } from 'lucide-react'

import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from '@/components/ui/dropdown-menu'
import { useAuthStore } from '@/store/auth-store'
import { User } from '@/types/user'
```

- [x] run build on local and passed
- [ ] build does not exceed 500kb

### CODE REVIEW

**Comment by hrithiqball** [comment]
@Kyziq try build using pnpm run build

**Comment by kyziq** [comment]
> @Kyziq try build using pnpm run build

dahh

image

image

**Comment by hrithiqball** [comment]
@Kyziq use git convention for other pr

**Comment by kyziq** [comment]
Alamak was used to gitmoji and commit message hehe 🤭

**Pull request merged**
